/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *toolbuttonEjecutar;
  GtkWidget *toolbuttonAdicionarProceso;
  GtkWidget *toolbuttonAcercade;
  GtkWidget *toolbuttonSalir;
  GtkWidget *drawingarea1;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window1, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (window1), _("Simulador de Memoria"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH_HORIZ);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  tmp_image = gtk_image_new_from_stock ("gtk-media-play", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbuttonEjecutar = (GtkWidget*) gtk_tool_button_new (tmp_image, "");
  gtk_widget_show (toolbuttonEjecutar);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbuttonEjecutar);

  tmp_image = gtk_image_new_from_stock ("gtk-add", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbuttonAdicionarProceso = (GtkWidget*) gtk_tool_button_new (tmp_image, "");
  gtk_widget_show (toolbuttonAdicionarProceso);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbuttonAdicionarProceso);

  tmp_image = gtk_image_new_from_stock ("gtk-about", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbuttonAcercade = (GtkWidget*) gtk_tool_button_new (tmp_image, "");
  gtk_widget_show (toolbuttonAcercade);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbuttonAcercade);

  tmp_image = gtk_image_new_from_stock ("gtk-quit", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbuttonSalir = (GtkWidget*) gtk_tool_button_new (tmp_image, "");
  gtk_widget_show (toolbuttonSalir);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbuttonSalir);

  drawingarea1 = gtk_drawing_area_new ();
  gtk_widget_show (drawingarea1);
  gtk_box_pack_start (GTK_BOX (vbox1), drawingarea1, TRUE, TRUE, 0);

  g_signal_connect ((gpointer) window1, "destroy",
                    G_CALLBACK (on_window1_destroy),
                    NULL);
  g_signal_connect ((gpointer) toolbuttonEjecutar, "clicked",
                    G_CALLBACK (on_toolbuttonEjecutar_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbuttonAdicionarProceso, "clicked",
                    G_CALLBACK (on_toolbuttonAdicionarProceso_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbuttonAcercade, "clicked",
                    G_CALLBACK (on_toolbuttonAcercade_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbuttonSalir, "clicked",
                    G_CALLBACK (on_toolbuttonSalir_clicked),
                    NULL);
  g_signal_connect ((gpointer) drawingarea1, "configure_event",
                    G_CALLBACK (on_drawingarea1_configure_event),
                    NULL);
  g_signal_connect ((gpointer) drawingarea1, "expose_event",
                    G_CALLBACK (on_drawingarea1_expose_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (window1, toolbuttonEjecutar, "toolbuttonEjecutar");
  GLADE_HOOKUP_OBJECT (window1, toolbuttonAdicionarProceso, "toolbuttonAdicionarProceso");
  GLADE_HOOKUP_OBJECT (window1, toolbuttonAcercade, "toolbuttonAcercade");
  GLADE_HOOKUP_OBJECT (window1, toolbuttonSalir, "toolbuttonSalir");
  GLADE_HOOKUP_OBJECT (window1, drawingarea1, "drawingarea1");

  return window1;
}

GtkWidget*
create_aboutdialog (void)
{
  GtkWidget *aboutdialog;
  const gchar *authors[] = {
    "Erick Oswaldo Gallegos P\303\251rez.",
    "UNIVERSIDAD DEL ISTMO, CAMPUS TEHUANTEPEC. ",
    "INGENIER\303\215A EN COMPUTACI\303\223N. GRUPO 604.",
    NULL
  };
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator-credits");
  GdkPixbuf *aboutdialog_logo_pixbuf;

  aboutdialog = gtk_about_dialog_new ();
  gtk_container_set_border_width (GTK_CONTAINER (aboutdialog), 5);
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (aboutdialog), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (aboutdialog), _("Simmem"));
  gtk_about_dialog_set_copyright (GTK_ABOUT_DIALOG (aboutdialog), _("Erick Oswaldo Gallegos P\303\251rez.\nUNIVERSIDAD DEL ISTMO CAMPUS TEHUANTEPEC.\nINGENIER\303\215A EN COMPUTACI\303\223N.\nMATERIA: SISTEMAS OPERATIVOS.\nGRUPO: 604."));
  gtk_about_dialog_set_comments (GTK_ABOUT_DIALOG (aboutdialog), _("Peque\303\261o simulador de memoria, primero el trabajo m\303\241s corto."));
  gtk_about_dialog_set_authors (GTK_ABOUT_DIALOG (aboutdialog), authors);
  gtk_about_dialog_set_translator_credits (GTK_ABOUT_DIALOG (aboutdialog), translators);
  aboutdialog_logo_pixbuf = create_pixbuf ("unistmo.png");
  gtk_about_dialog_set_logo (GTK_ABOUT_DIALOG (aboutdialog), aboutdialog_logo_pixbuf);

  g_signal_connect ((gpointer) aboutdialog, "destroy",
                    G_CALLBACK (on_aboutdialog_destroy),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aboutdialog, aboutdialog, "aboutdialog");

  return aboutdialog;
}

GtkWidget*
create_dialogAdicionar (void)
{
  GtkWidget *dialogAdicionar;
  GtkWidget *dialog_vbox1;
  GtkWidget *table1;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *entryPID;
  GtkWidget *entryPagCod;
  GtkWidget *entryPagDat;
  GtkWidget *entryPagPil;
  GtkWidget *entryTiempo;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  dialogAdicionar = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialogAdicionar), _("Adicionar Proceso:"));
  gtk_window_set_type_hint (GTK_WINDOW (dialogAdicionar), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialogAdicionar), FALSE);

  dialog_vbox1 = GTK_DIALOG (dialogAdicionar)->vbox;
  gtk_widget_show (dialog_vbox1);

  table1 = gtk_table_new (5, 2, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), table1, TRUE, TRUE, 0);

  label1 = gtk_label_new (_("Identificador de Proceso"));
  gtk_widget_show (label1);
  gtk_table_attach (GTK_TABLE (table1), label1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);

  label2 = gtk_label_new (_("No. p\303\241ginas de c\303\263digo:"));
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table1), label2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);

  label3 = gtk_label_new (_("No. p\303\241ginas de datos:"));
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table1), label3, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);

  label4 = gtk_label_new (_("No. p\303\241ginas de pila:"));
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  label5 = gtk_label_new (_("Tiempo de llegada:"));
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table1), label5, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  entryPID = gtk_entry_new ();
  gtk_widget_show (entryPID);
  gtk_table_attach (GTK_TABLE (table1), entryPID, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPID), 9679);

  entryPagCod = gtk_entry_new ();
  gtk_widget_show (entryPagCod);
  gtk_table_attach (GTK_TABLE (table1), entryPagCod, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPagCod), 9679);

  entryPagDat = gtk_entry_new ();
  gtk_widget_show (entryPagDat);
  gtk_table_attach (GTK_TABLE (table1), entryPagDat, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPagDat), 9679);

  entryPagPil = gtk_entry_new ();
  gtk_widget_show (entryPagPil);
  gtk_table_attach (GTK_TABLE (table1), entryPagPil, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPagPil), 9679);

  entryTiempo = gtk_entry_new ();
  gtk_widget_show (entryTiempo);
  gtk_table_attach (GTK_TABLE (table1), entryTiempo, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryTiempo), 9679);

  dialog_action_area1 = GTK_DIALOG (dialogAdicionar)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialogAdicionar), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialogAdicionar), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialogAdicionar, dialogAdicionar, "dialogAdicionar");
  GLADE_HOOKUP_OBJECT_NO_REF (dialogAdicionar, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialogAdicionar, table1, "table1");
  GLADE_HOOKUP_OBJECT (dialogAdicionar, label1, "label1");
  GLADE_HOOKUP_OBJECT (dialogAdicionar, label2, "label2");
  GLADE_HOOKUP_OBJECT (dialogAdicionar, label3, "label3");
  GLADE_HOOKUP_OBJECT (dialogAdicionar, label4, "label4");
  GLADE_HOOKUP_OBJECT (dialogAdicionar, label5, "label5");
  GLADE_HOOKUP_OBJECT (dialogAdicionar, entryPID, "entryPID");
  GLADE_HOOKUP_OBJECT (dialogAdicionar, entryPagCod, "entryPagCod");
  GLADE_HOOKUP_OBJECT (dialogAdicionar, entryPagDat, "entryPagDat");
  GLADE_HOOKUP_OBJECT (dialogAdicionar, entryPagPil, "entryPagPil");
  GLADE_HOOKUP_OBJECT (dialogAdicionar, entryTiempo, "entryTiempo");
  GLADE_HOOKUP_OBJECT_NO_REF (dialogAdicionar, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialogAdicionar, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (dialogAdicionar, okbutton1, "okbutton1");

  return dialogAdicionar;
}

